### ISSUE TITLE
NameError: uninitialized constant TestProf::Ext::ActiveRecordRefind::ActiveRecord

### ISSUE THREAD

**Issue by NicoSa** [palkan/test-prof#162]
**Ruby Version:** ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-linux-musl]

**Framework Version (RSpec, Minitest, FactoryGirl, Rails, whatever):** Rails 6.0.0

**TestProf Version:** 0.10.0

### What did you do?

Tried to require the `let_it_be` in our `spec_helper.rb` by adding this line at the top `require 'test_prof/recipes/rspec/let_it_be'`.

### What did you expect to happen?

I expected to be able to use `let_it_be` in my rspec tests.

### What actually happened?

```
An error occurred while loading spec_helper.
Failure/Error: require "test_prof/recipes/rspec/let_it_be"

NameError:
  uninitialized constant TestProf::Ext::ActiveRecordRefind::ActiveRecord
  /usr/local/bundle/gems/test-prof-0.10.0/lib/test_prof/ext/active_record_refind.rb:7:in `<module:ActiveRecordRefind>'
  /usr/local/bundle/gems/test-prof-0.10.0/lib/test_prof/ext/active_record_refind.rb:6:in `<module:Ext>'
  /usr/local/bundle/gems/test-prof-0.10.0/lib/test_prof/ext/active_record_refind.rb:4:in `<module:TestProf>'
  /usr/local/bundle/gems/test-prof-0.10.0/lib/test_prof/ext/active_record_refind.rb:3:in `<top (required)>'
  /usr/local/bundle/gems/test-prof-0.10.0/lib/test_prof/recipes/rspec/let_it_be.rb:130:in `require'
  /usr/local/bundle/gems/test-prof-0.10.0/lib/test_prof/recipes/rspec/let_it_be.rb:130:in `<top (required)>'
  ./spec/spec_helper.rb:5:in `require'
  ./spec/spec_helper.rb:5:in `<top (required)>'
/usr/local/bundle/gems/test-prof-0.10.0/lib/test_prof/recipes/rspec/let_it_be.rb:86: warning: already initialized constant TestProf::LetItBe::PREFIX
/usr/local/bundle/gems/test-prof-0.10.0/lib/test_prof/recipes/rspec/let_it_be.rb:86: warning: previous definition of PREFIX was here

An error occurred while loading ./spec/controllers/v2/our_controller_spec.rb.
Failure/Error: require "test_prof/recipes/rspec/let_it_be"

NameError:
  uninitialized constant TestProf::Ext::ActiveRecordRefind::ActiveRecord
  /usr/local/bundle/gems/test-prof-0.10.0/lib/test_prof/ext/active_record_refind.rb:7:in `<module:ActiveRecordRefind>'
  /usr/local/bundle/gems/test-prof-0.10.0/lib/test_prof/ext/active_record_refind.rb:6:in `<module:Ext>'
  /usr/local/bundle/gems/test-prof-0.10.0/lib/test_prof/ext/active_record_refind.rb:4:in `<module:TestProf>'
  /usr/local/bundle/gems/test-prof-0.10.0/lib/test_prof/ext/active_record_refind.rb:3:in `<top (required)>'
  /usr/local/bundle/gems/test-prof-0.10.0/lib/test_prof/recipes/rspec/let_it_be.rb:130:in `require'
  /usr/local/bundle/gems/test-prof-0.10.0/lib/test_prof/recipes/rspec/let_it_be.rb:130:in `<top (required)>'
  ./spec/spec_helper.rb:5:in `require'
  ./spec/spec_helper.rb:5:in `<top (required)>'
  ./spec/rails_helper.rb:24:in `require'
  ./spec/rails_helper.rb:24:in `<top (required)>'
  ./spec/controllers/v2/our_controller_spec.rb:3:in `require'
  ./spec/controllers/v2/our_controller_spec.rb:3:in `<top (required)>'
No examples found.


Finished in 0.00188 seconds (files took 0.82622 seconds to load)
0 examples, 0 failures, 2 errors occurred outside of examples

Command exited with non-zero status 1
real	0m 1.24s
user	0m 0.82s
sys	0m 0.17s
```

**Comment by palkan** [comment]
Thanks for the report! Fixed in #163
