### ISSUE TITLE
Ruby Interpreter Error with TEST_RUBY_PROF=call_stack

### ISSUE THREAD

**Issue by MFoster** [palkan/test-prof#41]
### Environment:
Ruby 2.3.4

Rails 4.2.0, RSpec 3.1.0

TestProf 0.4.0

### Executed:
`bundle exec spec TEST_RUBY_PROF=call_stack`
### Expected:
To generate a call stack report on test suite.
### Actual:
Catastrophic failure...
```
7fc1ad0cb000-7fc1ad0cd000 r-xp 00000000 08:01 392504                     /lib/x86_64-linux-gnu/libdl-2.13.so
7fc1ad0cd000-7fc1ad2cd000 ---p 00002000 08:01 392504                     /lib/x86_64-linux-gnu/libdl-2.13.so
7fc1ad2cd000-7fc1ad2ce000 r--p 00002000 08:01 392504                     /lib/x86_64-linux-gnu/libdl-2.13.so
7fc1ad2ce000-7fc1ad2cf000 rw-p 00003000 08:01 392504                     /lib/x86_64-linux-gnu/libdl-2.13.so
7fc1ad2cf000-7fc1ad2d6000 r-xp 00000000 08:01 392517                     /lib/x86_64-linux-gnu/librt-2.13.so
7fc1ad2d6000-7fc1ad4d5000 ---p 00007000 08:01 392517                     /lib/x86_64-linux-gnu/librt-2.13.so
7fc1ad4d5000-7fc1ad4d6000 r--p 00006000 08:01 392517                     /lib/x86_64-linux-gnu/librt-2.13.so
7fc1ad4d6000-7fc1ad4d7000 rw-p 00007000 08:01 392517                     /lib/x86_64-linux-gnu/librt-2.13.so
7fc1ad4d7000-7fc1ad4ee000 r-xp 00000000 08:01 392494                     /lib/x86_64-linux-gnu/libpthread-2.13.so
7fc1ad4ee000-7fc1ad6ed000 ---p 00017000 08:01 392494                     /lib/x86_64-linux-gnu/libpthread-2.13.so
7fc1ad6ed000-7fc1ad6ee000 r--p 00016000 08:01 392494                     /lib/x86_64-linux-gnu/libpthread-2.13.so
7fc1ad6ee000-7fc1ad6ef000 rw-p 00017000 08:01 392494                     /lib/x86_64-linux-gnu/libpthread-2.13.so
7fc1ad6ef000-7fc1ad6f3000 rw-p 00000000 00:00 0
7fc1ad6f3000-7fc1ad9af000 r-xp 00000000 08:01 23032                      /usr/local/lib/libruby.so.2.3.0
7fc1ad9af000-7fc1adbae000 ---p 002bc000 08:01 23032                      /usr/local/lib/libruby.so.2.3.0
7fc1adbae000-7fc1adbb7000 rw-p 002bb000 08:01 23032                      /usr/local/lib/libruby.so.2.3.0
7fc1adbb7000-7fc1adbc8000 rw-p 00000000 00:00 0
7fc1adbc8000-7fc1adbe8000 r-xp 00000000 08:01 392497                     /lib/x86_64-linux-gnu/ld-2.13.so
7fc1adbfe000-7fc1adc21000 r--s 00000000 08:01 23031                      /usr/local/bin/ruby
7fc1adc21000-7fc1adc63000 rw-p 00000000 00:00 0
7fc1adc63000-7fc1addda000 r--p 00000000 08:01 1262                       /usr/lib/locale/locale-archive
7fc1addda000-7fc1adddf000 rw-p 00000000 00:00 0
7fc1adde1000-7fc1adde5000 r-xp 00000000 00:00 0
7fc1adde5000-7fc1adde7000 rw-p 00000000 00:00 0
7fc1adde7000-7fc1adde8000 r--p 0001f000 08:01 392497                     /lib/x86_64-linux-gnu/ld-2.13.so
7fc1adde8000-7fc1adde9000 rw-p 00020000 08:01 392497                     /lib/x86_64-linux-gnu/ld-2.13.so
7fc1adde9000-7fc1addea000 rw-p 00000000 00:00 0
7fff3cf2f000-7fff3d72e000 rw-p 00000000 00:00 0                          [stack]
7fff3d7b6000-7fff3d7b7000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]


[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
For details: http://www.ruby-lang.org/bugreport.html

/usr/local/bin/ruby -I/home/vagrant/.gem/gems/rspec-core-3.1.5/lib:/home/vagrant/.gem/gems/rspec-support-3.1.1/lib /home/vagrant/.gem/gems/rspec-core-3.1.5/exe/rspec spec/concepts/acquisition/ failed
rake aborted!
TypeError: no implicit conversion from nil to integer
/home/vagrant/.gem/gems/rspec-core-3.1.5/lib/rspec/core/rake_task.rb:97:in `exit'
/home/vagrant/.gem/gems/rspec-core-3.1.5/lib/rspec/core/rake_task.rb:97:in `run_task'
/home/vagrant/.gem/gems/rspec-core-3.1.5/lib/rspec/core/rake_task.rb:109:in `block (2 levels) in define'
/home/vagrant/.gem/gems/rspec-core-3.1.5/lib/rspec/core/rake_task.rb:107:in `block in define'
/home/vagrant/.gem/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:74:in `load'
/home/vagrant/.gem/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:74:in `kernel_load'
/home/vagrant/.gem/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:27:in `run'
/home/vagrant/.gem/gems/bundler-1.15.4/lib/bundler/cli.rb:362:in `exec'
/home/vagrant/.gem/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/vagrant/.gem/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/home/vagrant/.gem/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/home/vagrant/.gem/gems/bundler-1.15.4/lib/bundler/cli.rb:22:in `dispatch'
/home/vagrant/.gem/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/home/vagrant/.gem/gems/bundler-1.15.4/lib/bundler/cli.rb:13:in `start'
/home/vagrant/.gem/gems/bundler-1.15.4/exe/bundle:30:in `block in <top (required)>'
/home/vagrant/.gem/gems/bundler-1.15.4/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/home/vagrant/.gem/gems/bundler-1.15.4/exe/bundle:22:in `<top (required)>'
/usr/local/bin/bundle:22:in `load'
/usr/local/bin/bundle:22:in `<main>'
```

**Comment by palkan** [comment]
Wow.. Unfortunately, stacktrace doesn't tell us anything(

What is the `spec` command? Looks like it invokes `rake`.

What if you run ` TEST_RUBY_PROF=call_stack rspec  ...`?

**Comment by lisovskyvlad** [comment]
I also don't have any report generated with next gems:

```
gem 'spring', '~> 2.0', '>= 2.0.2'
gem 'spring-commands-rspec', '~> 1.0', '>= 1.0.4'
gem 'spring-watcher-listen', '~> 2.0.0'
```

But with commented, the report is generated :)

**Comment by palkan** [comment]
@lisovskyvlad Looks more like https://github.com/palkan/test-prof/issues/47. Have you tried to run with `DISABLE_SPRING=1 ...`? What is the output when no report generated?

**Comment by lisovskyvlad** [comment]
Hey @palkan, big thanks for the quick response.

with commented spring gems, I have:
```
[TEST PROF INFO] RubyProf enabled
...
[TEST PROF INFO] RubyProf report generated: tmp/test_prof/ruby-prof-report-call_stack-wall-total-1510064896.html
```

with spring, just nothing. Only usual test running and no any footprint of ruby_prof.

When I run
`TEST_RUBY_PROF=call_stack DISABLE_SPRING=1 bundle exec rspec spec/services/factory_works/v2`

I also got the same with previous - nothing.

**Comment by palkan** [comment]
@lisovskyvlad Does it depend on the exact gems you're commenting out? I.e. does it work with just "spring" enabled and two others _turned off_?

Unfortunately, I cannot reproduce these problems, in all my projects I use both `spring` and `test-prof`, and everything works correctly.

**Comment by palkan** [comment]
Closing as stale.
Feel free to re-open if the problem still exists in the latest version.
