### ISSUE TITLE
Unitialized constant `TestProf::FactoryBot`

### ISSUE THREAD

**Issue by martinstreicher** [palkan/test-prof#64]
### Tell us about your environment

**Ruby Version:** 2.4.2

**Framework Version (RSpec, Minitest, FactoryGirl, Rails, whatever):** Rspec 3.7.0, FactoryBot 4.8.2, Rails 5.2.pre

**TestProf Version:** 0.4.8 

### What did you do? 

I am following the instructions to add the Factory Default recipe. 

### What did you expect to happen?

Code would load and work. 

### What actually happened?

Get an error...

```
/Users/mss67/.rvm/gems/ruby-2.4.2@memberhub-commerce-api/gems/test-prof-0.4.8/lib/test_prof/factory_default/factory_bot_patch.rb:6:in `<module:RunnerExt>': uninitialized constant TestProf::FactoryBot (NameError)
Did you mean?  TestProf::FactoryDefault
	from /Users/mss67/.rvm/gems/ruby-2.4.2@memberhub-commerce-api/gems/test-prof-0.4.8/lib/test_prof/factory_default/factory_bot_patch.rb:5:in `<module:FactoryDefault>'
	from /Users/mss67/.rvm/gems/ruby-2.4.2@memberhub-commerce-api/gems/test-prof-0.4.8/lib/test_prof/factory_default/factory_bot_patch.rb:4:in `<module:TestProf>'
	from /Users/mss67/.rvm/gems/ruby-2.4.2@memberhub-commerce-api/gems/test-prof-0.4.8/lib/test_prof/factory_default/factory_bot_patch.rb:3:in `<top (required)>'
	from /Users/mss67/.rvm/rubies/ruby-2.4.2/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /Users/mss67/.rvm/rubies/ruby-2.4.2/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /Users/mss67/.rvm/gems/ruby-2.4.2@memberhub-commerce-api/gems/test-prof-0.4.8/lib/test_prof/factory_default.rb:3:in `<top (required)>'
	from /Users/mss67/.rvm/rubies/ruby-2.4.2/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /Users/mss67/.rvm/rubies/ruby-2.4.2/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /Users/mss67/.rvm/gems/ruby-2.4.2@memberhub-commerce-api/gems/test-prof-0.4.8/lib/test_prof/recipes/rspec/factory_default.rb:3:in `<top (required)>'
	from /Users/mss67/.rvm/rubies/ruby-2.4.2/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:135:in `require'
	from /Users/mss67/.rvm/rubies/ruby-2.4.2/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
	from /Users/mss67/.rvm/rubies/ruby-2.4.2/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from /Users/mss67/projects/5p/memberhub-commerce-api/spec/spec_helper.rb:3:in `<top (required)>'
```

**Comment by martinstreicher** [comment]
I have tried several permutations of `require` to address the issue to no avail. The instructions for `let_it_be` worked flawlessly. I think this is a load order issue.

**Comment by martinstreicher** [comment]
Thanks for taking a look, @palkan. It may just be ordering of the require statement.

**Comment by palkan** [comment]
I've pushed an updated version, please, try it. The problem should be fixed now.

**Comment by martinstreicher** [comment]
I added 

```
require 'test_prof/recipes/rspec/factory_default'
```

as the first line to my _spec_helper.rb_ and then ran _rspec_. 

```
NoMethodError: private method `require' called for TestProf:Module
  /Users/strike/.rvm/gems/ruby-2.4.2@memberhub-commerce-api/gems/test-prof-0.4.9/lib/test_prof/factory_bot.rb:7:in `block in <module:TestProf>'
  /Users/strike/.rvm/gems/ruby-2.4.2@memberhub-commerce-api/gems/test-prof-0.4.9/lib/test_prof/factory_bot.rb:6:in `each'
  /Users/strike/.rvm/gems/ruby-2.4.2@memberhub-commerce-api/gems/test-prof-0.4.9/lib/test_prof/factory_bot.rb:6:in `find'
  /Users/strike/.rvm/gems/ruby-2.4.2@memberhub-commerce-api/gems/test-prof-0.4.9/lib/test_prof/factory_bot.rb:6:in `<module:TestProf>'
  /Users/strike/.rvm/gems/ruby-2.4.2@memberhub-commerce-api/gems/test-prof-0.4.9/lib/test_prof/factory_bot.rb:3:in `<top (required)>'
  /Users/strike/.rvm/gems/ruby-2.4.2@memberhub-commerce-api/gems/test-prof-0.4.9/lib/test_prof/factory_default.rb:3:in `require'
  /Users/strike/.rvm/gems/ruby-2.4.2@memberhub-commerce-api/gems/test-prof-0.4.9/lib/test_prof/factory_default.rb:3:in `<top (required)>'
  /Users/strike/.rvm/gems/ruby-2.4.2@memberhub-commerce-api/gems/test-prof-0.4.9/lib/test_prof/recipes/rspec/factory_default.rb:3:in `require'
  /Users/strike/.rvm/gems/ruby-2.4.2@memberhub-commerce-api/gems/test-prof-0.4.9/lib/test_prof/recipes/rspec/factory_default.rb:3:in `<top (required)>'
  /Users/strike/projects/5p/memberhub-commerce-api/spec/spec_helper.rb:3:in `require'
  /Users/strike/projects/5p/memberhub-commerce-api/spec/spec_helper.rb:3:in `<top (required)>'
```

**Comment by palkan** [comment]
Hm, looks like the core functionality is not loaded; try to add `require "test-prof"` before requiring any recipe.

**Comment by martinstreicher** [comment]
I think I may have a configuration that works. One moment...

**Comment by martinstreicher** [comment]
If I do this at the top of my _rails_helper.rb_, there is no error. What do you require in your _spec_helper.rb_?


```
ENV['RAILS_ENV'] ||= 'test'

require File.expand_path('../config/environment', __dir__)
require 'spec_helper'
require 'rspec/rails'
require 'jsonapi-serializers'
require 'test_prof/recipes/rspec/factory_default'
require 'test_prof/recipes/rspec/let_it_be'
```

**Comment by palkan** [comment]
And how did the previous, failing, version look like?

**Comment by martinstreicher** [comment]
This is the top of _spec_helper.rb_:

```
# frozen_string_literal: true

require 'timecop'
require 'webmock/rspec'
require 'test-prof'
require 'test_prof/recipes/rspec/factory_default'
require 'test_prof/recipes/rspec/let_it_be'
```

And that produces...

```
/Users/strike/.rvm/gems/ruby-2.4.2@memberhub-commerce-api/gems/test-prof-0.4.9/lib/test_prof/factory_default/factory_bot_patch.rb:6:in `<module:RunnerExt>': uninitialized constant TestProf::FactoryBot (NameError)
Did you mean?  TestProf::FactoryProf
	from /Users/strike/.rvm/gems/ruby-2.4.2@memberhub-commerce-api/gems/test-prof-0.4.9/lib/test_prof/factory_default/factory_bot_patch.rb:5:in `<module:FactoryDefault>'
	from /Users/strike/.rvm/gems/ruby-2.4.2@memberhub-commerce-api/gems/test-prof-0.4.9/lib/test_prof/factory_default/factory_bot_patch.rb:4:in `<module:TestProf>'
	from /Users/strike/.rvm/gems/ruby-2.4.2@memberhub-commerce-api/gems/test-prof-0.4.9/lib/test_prof/factory_default/factory_bot_patch.rb:3:in `<top (required)>'
	from /Users/strike/.rvm/rubies/ruby-2.4.2/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /Users/strike/.rvm/rubies/ruby-2.4.2/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /Users/strike/.rvm/gems/ruby-2.4.2@memberhub-commerce-api/gems/test-prof-0.4.9/lib/test_prof/factory_default.rb:4:in `<top (required)>'
	from /Users/strike/.rvm/rubies/ruby-2.4.2/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /Users/strike/.rvm/rubies/ruby-2.4.2/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /Users/strike/.rvm/gems/ruby-2.4.2@memberhub-commerce-api/gems/test-prof-0.4.9/lib/test_prof/recipes/rspec/factory_default.rb:3:in `<top (required)>'
	from /Users/strike/.rvm/rubies/ruby-2.4.2/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /Users/strike/.rvm/rubies/ruby-2.4.2/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /Users/strike/projects/5p/memberhub-commerce-api/spec/spec_helper.rb:6:in `<top (required)>'

```

**Comment by palkan** [comment]
Ok, I got it. You had to load `factory_bot` (or `factory_girl`) manually.

For Rails applications it's better to load all the plugins in `rails_helper` after `environment`.

I'd better add smth like "Make sure you're requiring factory_default after FactoryBot" to the guide.
