### ISSUE TITLE
Ruby prof "inconsistent call tree" error

### ISSUE THREAD

**Issue by dgilperez** [palkan/test-prof#87]
### Tell us about your environment

**Ruby Version:** 2.5.1
**Framework Version:** RSpec 3.6.0
**TestProf Version:** 0.6.0
**RubyProf Version:** 0.17.0

Error is independent from using spring or not. 

### What did you do?

`TEST_RUBY_PROF=call_stack bin/rspec spec/models`

### What did you expect to happen?

A ruby-prof output :P

### What actually happened?

Specs run correctly, but after the build there was an error with the following stack: 

```
Running via Spring preloader in process 75237
[TEST PROF INFO] Activating TEST_RUBY_PROF with `Spring.after_fork`
[TEST PROF INFO] RubyProf enabled

... build running ...

Finished in X minute Y seconds (files took 4.16 seconds to load)
Z examples, 0 failures, 1 pending

Randomized with seed 31213
DEPRECATION WARNING: Method 'eliminate_methods!' is dprecated
Please call 'exclude_methods!' before starting the profile run instead.
Traceback (most recent call last):
	80: from -e:1:in `<main>'
	79: from /Users/dgilperez/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	78: from /Users/dgilperez/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	77: from /Users/dgilperez/.rvm/gems/ruby-2.5.1/gems/test-prof-0.6.0/lib/test_prof/ruby_prof.rb:171:in `block in run'
	76: from /Users/dgilperez/.rvm/gems/ruby-2.5.1/gems/test-prof-0.6.0/lib/test_prof/ruby_prof.rb:108:in `dump'
	75: from /Users/dgilperez/.rvm/gems/ruby-2.5.1/gems/ruby-prof-0.17.0/lib/ruby-prof/profile/legacy_method_elimination.rb:13:in `eliminate_methods!'
	74: from /Users/dgilperez/.rvm/gems/ruby-2.5.1/gems/ruby-prof-0.17.0/lib/ruby-prof/profile/legacy_method_elimination.rb:13:in `each'
	73: from /Users/dgilperez/.rvm/gems/ruby-2.5.1/gems/ruby-prof-0.17.0/lib/ruby-prof/profile/legacy_method_elimination.rb:14:in `block in eliminate_methods!'
	72: from /Users/dgilperez/.rvm/gems/ruby-2.5.1/gems/ruby-prof-0.17.0/lib/ruby-prof/profile/legacy_method_elimination.rb:14:in `each'
	71: from /Users/dgilperez/.rvm/gems/ruby-2.5.1/gems/ruby-prof-0.17.0/lib/ruby-prof/profile/legacy_method_elimination.rb:14:in `block (2 levels) in eliminate_methods!'
	70: from /Users/dgilperez/.rvm/gems/ruby-2.5.1/gems/ruby-prof-0.17.0/lib/ruby-prof/profile/legacy_method_elimination.rb:40:in `eliminate_methods'
	69: from /Users/dgilperez/.rvm/gems/ruby-2.5.1/gems/ruby-prof-0.17.0/lib/ruby-prof/method_info.rb:116:in `eliminate!'
	68: from /Users/dgilperez/.rvm/gems/ruby-2.5.1/gems/ruby-prof-0.17.0/lib/ruby-prof/method_info.rb:116:in `each'
	67: from /Users/dgilperez/.rvm/gems/ruby-2.5.1/gems/ruby-prof-0.17.0/lib/ruby-prof/method_info.rb:116:in `block in eliminate!'
	66: from /Users/dgilperez/.rvm/gems/ruby-2.5.1/gems/ruby-prof-0.17.0/lib/ruby-prof/call_info.rb:74:in `eliminate!'
	65: from /Users/dgilperez/.rvm/gems/ruby-2.5.1/gems/ruby-prof-0.17.0/lib/ruby-prof/call_info.rb:74:in `each'
	64: from /Users/dgilperez/.rvm/gems/ruby-2.5.1/gems/ruby-prof-0.17.0/lib/ruby-prof/call_info.rb:76:in `block in eliminate!'
	63: from /Users/dgilperez/.rvm/gems/ruby-2.5.1/gems/ruby-prof-0.17.0/lib/ruby-prof/call_info.rb:102:in `merge_call_tree'
	62: from /Users/dgilperez/.rvm/gems/ruby-2.5.1/gems/ruby-prof-0.17.0/lib/ruby-prof/call_info.rb:102:in `each'
	61: from /Users/dgilperez/.rvm/gems/ruby-2.5.1/gems/ruby-prof-0.17.0/lib/ruby-prof/call_info.rb:105:in `block in merge_call_tree'
	60: from /Users/dgilperez/.rvm/gems/ruby-2.5.1/gems/ruby-prof-0.17.0/lib/ruby-prof/call_info.rb:102:in `merge_call_tree'
	59: from /Users/dgilperez/.rvm/gems/ruby-2.5.1/gems/ruby-prof-0.17.0/lib/ruby-prof/call_info.rb:102:in `each'
	58: from /Users/dgilperez/.rvm/gems/ruby-2.5.1/gems/ruby-prof-0.17.0/lib/ruby-prof/call_info.rb:105:in `block in merge_call_tree'
	57: from /Users/dgilperez/.rvm/gems/ruby-2.5.1/gems/ruby-prof-0.17.0/lib/ruby-prof/call_info.rb:102:in `merge_call_tree'
	56: from /Users/dgilperez/.rvm/gems/ruby-2.5.1/gems/ruby-prof-0.17.0/lib/ruby-prof/call_info.rb:102:in `each'
	55: from /Users/dgilperez/.rvm/gems/ruby-2.5.1/gems/ruby-prof-0.17.0/lib/ruby-prof/call_info.rb:105:in `block in merge_call_tree'
	54: from /Users/dgilperez/.rvm/gems/ruby-2.5.1/gems/ruby-prof-0.17.0/lib/ruby-prof/call_info.rb:102:in `merge_call_tree'
	53: from /Users/dgilperez/.rvm/gems/ruby-2.5.1/gems/ruby-prof-0.17.0/lib/ruby-prof/call_info.rb:102:in `each'
	52: from /Users/dgilperez/.rvm/gems/ruby-2.5.1/gems/ruby-prof-0.17.0/lib/ruby-prof/call_info.rb:105:in `block in merge_call_tree'
	51: from /Users/dgilperez/.rvm/gems/ruby-2.5.1/gems/ruby-prof-0.17.0/lib/ruby-prof/call_info.rb:102:in `merge_call_tree'
	50: from /Users/dgilperez/.rvm/gems/ruby-2.5.1/gems/ruby-prof-0.17.0/lib/ruby-prof/call_info.rb:102:in `each'
	49: from /Users/dgilperez/.rvm/gems/ruby-2.5.1/gems/ruby-prof-0.17.0/lib/ruby-prof/call_info.rb:105:in `block in merge_call_tree'
	48: from /Users/dgilperez/.rvm/gems/ruby-2.5.1/gems/ruby-prof-0.17.0/lib/ruby-prof/call_info.rb:102:in `merge_call_tree'
	47: from /Users/dgilperez/.rvm/gems/ruby-2.5.1/gems/ruby-prof-0.17.0/lib/ruby-prof/call_info.rb:102:in `each'
	46: from /Users/dgilperez/.rvm/gems/ruby-2.5.1/gems/ruby-prof-0.17.0/lib/ruby-prof/call_info.rb:105:in `block in merge_call_tree'
	45: from /Users/dgilperez/.rvm/gems/ruby-2.5.1/gems/ruby-prof-0.17.0/lib/ruby-prof/call_info.rb:102:in `merge_call_tree'
	44: from /Users/dgilperez/.rvm/gems/ruby-2.5.1/gems/ruby-prof-0.17.0/lib/ruby-prof/call_info.rb:102:in `each'
	43: from /Users/dgilperez/.rvm/gems/ruby-2.5.1/gems/ruby-prof-0.17.0/lib/ruby-prof/call_info.rb:105:in `block in merge_call_tree'
	42: from /Users/dgilperez/.rvm/gems/ruby-2.5.1/gems/ruby-prof-0.17.0/lib/ruby-prof/call_info.rb:102:in `merge_call_tree'

        .... same pattern for 40 lines ... 

	 1: from /Users/dgilperez/.rvm/gems/ruby-2.5.1/gems/ruby-prof-0.17.0/lib/ruby-prof/call_info.rb:103:in `block in merge_call_tree'
/Users/dgilperez/.rvm/gems/ruby-2.5.1/gems/ruby-prof-0.17.0/lib/ruby-prof/call_info.rb:91:in `find_call': inconsistent call tree (RuntimeError)
```

So this looks like a `ruby-prof` error? Maybe related to Ruby 2.5.1? Can anyone reproduce?

**Comment by palkan** [comment]
Looks like a problem with the deprecated `eliminate_methods!`.

I've upgraded  master version to use `exclude_methods!` instead, try to use it.

**Comment by dgilperez** [comment]
Working! Thanks a lot 👏
